#
# Sets Oh My Zsh options.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Set the key mapping style to 'emacs' or 'vi'.
zstyle ':omz:module:editor' keymap 'vi'

# Auto convert .... to ../..
zstyle ':omz:module:editor' dot-expansion 'no'

# Set case-sensitivity for completion, history lookup, etc.
zstyle ':omz:*:*' case-sensitive 'no'

# Color output (auto set to 'no' on dumb terminals).
zstyle ':omz:*:*' color 'yes'

# Auto set the tab and window titles.
zstyle ':omz:module:terminal' auto-title 'yes'


# Set the Zsh modules to load (man zshmodules).
# zstyle ':omz:load' zmodule 'attr' 'stat'

# Set the Zsh functions to load (man zshcontrib).
# zstyle ':omz:load' zfunction 'zargs' 'zmv'

# Set the Oh My Zsh modules to load (browse modules).
# The order matters.
zstyle ':omz:load' omodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'completion' \
  'prompt' \
  'tmux'

# Set the prompt theme to load.
# Setting it to 'random' loads a random theme.
# Auto set to 'off' on dumb terminals.
zstyle ':omz:module:prompt' theme 'steeef'

zstyle ':omz:module:tmux' auto-start 'yes'
# This will make you shout: OH MY ZSHELL!
#
source "$OMZ/init.zsh"

# Customize to your needs...
export EDITOR="vim"
export PAGER="less"
export BROWSER="chromium-browser"
export MOVPLAYER="vlc"
export SNDPLAYER="vlc"


for ext in h264 mpg wmv avi mkv mp4 mov; do alias -s $ext=$MOVPLAYER; done
for ext in wav mp3 ogg wma m4a mid; do alias -s $ext=$SNDPLAYER; done
for ext in html; do alias -s $ext=$BROWSER; done

export LANG=en_US.utf8

# force tmux to 256-color mode
alias tmux="tmux -2"

# hide python compiled bytecode and vim backup files in ls
alias ls='ls --hide="*.pyc" --hide="*~" --color=auto'
